//
//  Notice: This file is generated by the IOC tool. Please do not modify it manually.
//  Created by ioc-script on 2023/11/16 13:57:46.

import Foundation

public enum ServiceName: String, Codable, Equatable {
	/// login
	case Login = "login"
	/// logout
	case Logout = "logout"

}